# Generated by Django 2.2 on 2019-06-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0007_auto_20190612_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
