# Generated by Django 2.2 on 2019-06-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0012_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='href',
            field=models.CharField(default='/', max_length=50),
            preserve_default=False,
        ),
    ]
