# Generated by Django 2.2 on 2019-06-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0014_auto_20190616_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc1', models.CharField(blank=True, max_length=100)),
                ('desc2', models.CharField(blank=True, max_length=100)),
                ('desc3', models.CharField(blank=True, max_length=100)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='infos.Topic')),
            ],
        ),
    ]
