# Generated by Django 2.2 on 2019-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0015_opinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opinion',
            field=models.IntegerField(choices=[(-1, None), (0, 0), (1, 1), (2, 2)], default=-1),
            preserve_default=False,
        ),
    ]
