# Generated by Django 2.2 on 2019-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_auto_20190602_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='topic_pics/default.jpg', upload_to='topic_pics'),
        ),
    ]
