# Generated by Django 2.2 on 2019-06-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190615_1620'),
        ('infos', '0016_post_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='opinion',
            field=models.IntegerField(choices=[(-1, None), (0, 'Choice 1'), (1, 'Choice 2'), (2, 'Choice 3')]),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='infos.Post')),
            ],
        ),
    ]
